name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
env:
  DOTNET_VERSION: '6.0.1' # The .NET SDK version to use

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout from branch
    - uses: actions/checkout@v2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}        
    - name: Restore dependencies
      run: dotnet restore      
    - name: Build
      run: dotnet build --no-restore      
    - name: Test
      run: dotnet test --no-build --verbosity normal
